name: cypress-test-wait-on
on:
  workflow_dispatch:

jobs:

  start:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [18, 20]
    name: Angular on Node.js ${{ matrix.node }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'npx wait-on --timeout 60000 http://localhost:4200'
          browser: chrome

  start-default:
    runs-on: ubuntu-22.04
    name: Angular default Node.js
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'npx wait-on --timeout 60000 http://localhost:4200'
          browser: chrome
